### ISSUE TITLE
Custom element doesn't exist: list-card.

### ISSUE THREAD

**Issue by pr0fetul** [custom-cards/list-card#21]
Hi,
Awesome work man. 
I wanted to use your code with the RSS Feedparser, but I cannot make it work in the Lovelace card. 
the error is:
`Custom element doesn't exist: list-card.
columns:
  - add_link: link
    field: image
    title: ''
    type: image
  - field: title
    style:
      - white-space: nowrap
    title: Title
  - field: description
    title: Description
entity: sensor.hotnews_romania
feed_attribute: entries
title: HotNews Romania
type: 'custom:list-card'`

I am running HA 0.107 in docker. And since a couple versions ago, they changed the location of resources. I cannot figure where the resources should be placed. I think that this is my issue. 

Thank you for your time.

**Comment by iantrich** [comment]
Config -> Lovelace Dashboards -> Resources

If you don't see the resources tab, then you don't have advanced mode turned on. You can do that from your profile page.

The easier method is to just use HACS though and install it from there.

**Comment by pr0fetul** [comment]
Thank you very much. I missed that option - although having it set on advanced. Now, the error is gone, however, the card does not populate the entries from the feed. 
The card has:
`columns:
  - add_link: link
    field: image
    title: ''
    type: image
  - field: title
    style:
      - white-space: nowrap
    title: Title
  - field: description
    title: Description
entity: sensor.hotnews_romania
feed_attribute: entries
title: HotNews Romania
type: 'custom:list-card'`

And the sensor outputs:
`

sensor.hotnews_romania | 10 | entries:  - title: >-     Coronavirus Italia: 756 de persoane au murit în 24 de ore / Bilanțul total -     10.779   link: >-     https://www.hotnews.ro/stiri-coronavirus-23761880-coronavirus-italia-756-persoane-murit-24-ore-bilantul-total-10-779.htm   image: 'https://www.home-assistant.io/images/favicon-192x192-full.png' - title: >-     Bilanțul deceselor în România a ajuns la 42 / Este vorba de o femeie de 75     de ani și un bărbat de 82 de ani, ambii din Hunedoara / Niciunul nu avusese     contact cu un caz confirmat   link: >-     https://www.hotnews.ro/stiri-coronavirus-23761862-coronavirus-in-romania-decese-bilant-29-martie.htm   image: 'https://www.home-assistant.io/images/favicon-192x192-full.png'
-- | -- | --


`

**Comment by iantrich** [comment]
Can you try formatting your config using backticks on here, I can't really tell what your config looks like right now. https://guides.github.com/features/mastering-markdown/#syntax

**Comment by pr0fetul** [comment]
Hi Ian, 
I will try. So, the card config is:
`columns:
  - add_link: link
    field: image
    title: ''
    type: image
  - field: title
    style:
      - white-space: nowrap
    title: Title
  - field: description
    title: Description
entity: sensor.hotnews_romania
feed_attribute: entries
title: HotNews Romania
type: 'custom:list-card'`

Which is standard as per your instructions. And the sensor feed outputs the information like this:

`entries: 
- title: >-
    Germania: Numărul de cazuri de coronavirus a depășit 57.000, peste 450 de
    oameni au murit până acum
  link: >-
    https://www.hotnews.ro/stiri-coronavirus-23762779-coronavirus-germania-cazuri-decese.htm
  image: 'https://www.home-assistant.io/images/favicon-192x192-full.png'`

I hope it's better now.

**Comment by pr0fetul** [comment]
![card](https://user-images.githubusercontent.com/17175289/77881551-e8229580-7267-11ea-9110-0d578a045ead.JPG)
![sensor](https://user-images.githubusercontent.com/17175289/77881552-e8bb2c00-7267-11ea-9a57-636c5fc5ace3.JPG)

**Comment by pr0fetul** [comment]
Unfortunately I could not make it work :( it does not want to pick up the entries from the sensor. I cleared the browser's cache, I tried removing columns - it does not react unless I remove the sensor or the card - meaning the integration itself.

**Comment by iantrich** [comment]
Maybe it is cut off in your screenshot, but I don't see a description column.

This card really just need a re-write, which I started but have not yet finished. It is very finicky in its current form

**Comment by pr0fetul** [comment]
Indeed, the feeds do not have "description" as column, but even if I comment the description from the card, it does not react. 
I see, ok, no worries, I thought I did something "wrong"

**Comment by pr0fetul** [comment]
Hi Ian, 
I think i sort of managed to fix my issue. I edited the feedparser component to extract Title, URL and image, and in the custom card, I only ended up with: 
`columns:
  - add_link: link
    field: title
    style:
      - border: 1px solid red
        font-size: 13px
        white-space: normal
    title: Title
entity: sensor.hotnews_romania
feed_attribute: entries
title: HotNews
type: 'custom:list-card'`
It's not ideal, as images are only the ha favicon - not actual images, but it's workable for now: 
![image](https://user-images.githubusercontent.com/17175289/78142548-b6f7c000-7435-11ea-8d43-ec1fa30d9aab.png)

**Comment by MattLathropTL** [comment]
I am also having the issue of "Custom element doesn't exist: list-card.: I tried installing with HACS but it is reporting it failed to load. I also tried to just add the js as a resource and that failed as well. Any ideas?

**Comment by majorsl** [comment]
Same, just ran across this and it won't load.

**Comment by crimsdings** [comment]
Same

Home Assistant 0.118.5

![image](https://user-images.githubusercontent.com/886421/101505466-aad4e280-3974-11eb-9380-5afdd5f9afd3.png)
![image](https://user-images.githubusercontent.com/886421/101505504-b922fe80-3974-11eb-949e-4d69660240e5.png)
![image](https://user-images.githubusercontent.com/886421/101505559-c6d88400-3974-11eb-9470-ebdcd633f797.png)

**Comment by iantrich** [comment]
@crimsdings remove the dash in front of you and unindent accordingly
