### ISSUE TITLE
The table goes outside the boundaries of the card

### ISSUE THREAD

**Issue by Dmxsir** [custom-cards/list-card#32]
There's a way to fix this?
![card list](https://user-images.githubusercontent.com/36658595/106189009-63b6e100-61b0-11eb-9cb0-188a85981cb2.JPG)

```type: 'custom:list-card'
entity: sensor.seventeentrack_packages_in_transit
title: Packages
feed_attribute: packages
row_limit: 20
columns:
  - title: Name
    field: friendly_name
    style:
      - white-space: nowrap
  - title: Status
    field: status
    style:
      - white-space: nowrap
  - title: Trcking number
    field: tracking_number
  - title: More info
    field: info_text
    style:
      - white-space: nowrap
  - title: location
    field: location
```

**Comment by iantrich** [comment]
Card width cannot be changed, and you have info_text set to nowrap, to it can't squeeze to fit. Either wrap columns, decrease text-size or use a layout system that allows for larger card sizes, e.g. layout-card or Custom-Grid-View

**Comment by Dmxsir** [comment]
Thanks for the suggestion, I'll give it a try.
