### ISSUE TITLE
2021.7 HA update and new Python

### ISSUE THREAD

**Issue by feh123** [custom-cards/list-card#36]
Hi trying to update to 2021.7 from 2021.3 but list-card does not work. I believe this is because 2021.7 has the updated python. Will you be updating list-card? Currently I am just staying with 2021.3 as list-card works really well. Thanks.

**Comment by iantrich** [comment]
list-card is a JS element, nothing to do with Python. You thinking of feedparser?

**Comment by feh123** [comment]
Ahh - thanks - I see you have bumped that - I will try installing the new feedparser.
