### ISSUE TITLE
Small style request with headers

### ISSUE THREAD

**Issue by rpitera** [custom-cards/list-card#6]
Just a small point, but it would be nice if the headers were excluded from any styling done with the style option.  In my opinion, headers should remain untouched from any styling and should be in a bold font style by default.

Is this possible?

**Comment by iantrich** [comment]
Anything is possible. Just a matter of when I have the time 😃

**Comment by rpitera** [comment]
Understood!  I'd appreciate if you'd consider adding this to your list. 👍

**Comment by rpitera** [comment]
BTW, I did finally figure out a way to exclude results from my RSS using a free webservice called [SiftRSS](https://siftrss.com/).  You may want to include it in your read me as a resource.  Working great for me in concert with FeedParser.

**Comment by iantrich** [comment]
That looks pretty cool

**Comment by iantrich** [comment]
Added to info page

**Comment by rpitera** [comment]
Cool!  Glad I could give something back!

**Comment by rpitera** [comment]
Another suggestion, 32px of padding right and left are a little much.  I edited it to 5px in my local copy and it looks so much better and helps with the line breaks.  Please consider either changing it or making it an option that the user can control.  Thanks!  Hope to see at the next Frenck stream.

**Comment by iantrich** [comment]
PRs welcome :)

**Comment by rpitera** [comment]
Trust me, if I could code I would have gladly done a PR.  Sorry.  I could do a PR with just my changed settings, but I don't know if that would fly with others as well as an option setting would.  Should I just not suggest anything anymore?

**Comment by simonblau** [comment]
Hey, 
i don't want to open a new issue for this... is it possible do change the width of a column? I tried to add style to my column, but nothing happened, im a total noob regarding CSS. Just want my pictures to not look that pressed together

  - columns:
      - type: image
        add_link: link
        field: href
        title: '   '
        _**style:
                width: 90 px**_
      - add_link: link
        field: title
        title: '    '
    type: 'custom:list-card'
    row_limit: 5
    entity: sensor.feed_nachhaltigkeit
    title: Nachhaltigkeits Feed

In my lovelace config, the "width" line of course is indented.
Thank you very much

**Comment by iantrich** [comment]
I not going to promise anything, but FINALLY circling back around to the list-card. Going to do a full rewrite and will try to keep this all in mind

**Comment by iantrich** [comment]
Going to close this as all your style needs should be possible with this as a basis: https://community.home-assistant.io/t/lovelace-rss-feed-parser-plugin-list-card/64637/86. They went beyond what I would have thought of :)
